remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Maikelz-Haks
description: Welcome to my GitHub Pages repository. Here you can find my projects, tools, and resources about technology, cybersecurity, and development.
