remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Maikelz-Haks
description: Bienvenido a mi repositorio de GitHub Pages. Aquí podrás encontrar mis proyectos, herramientas y recursos sobre tecnología, seguridad informática y desarrollo.
